# Generated by Django 4.1.3 on 2022-12-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='client_list',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sales',
            name='order_list',
            field=models.JSONField(default=dict),
        ),
    ]
