# Generated by Django 4.1.3 on 2022-12-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_sales_client_list_alter_sales_order_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='client_list',
        ),
    ]
