# Generated by Django 4.1.3 on 2022-11-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="variant",
            field=models.CharField(default="exit", max_length=50),
            preserve_default=False,
        ),
    ]
