# Generated by Django 4.1.3 on 2022-11-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
