# Generated by Django 4.1.3 on 2022-12-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SorotanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
    ]
