# Generated by Django 4.1.3 on 2022-12-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_sorotanproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SorotanProduct',
        ),
    ]
