# Generated by Django 4.1.3 on 2022-12-03 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_sales_client_list'),
        ('clients', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='account.sales'),
        ),
        migrations.DeleteModel(
            name='MockSales',
        ),
    ]
