# Generated by Django 4.1.3 on 2022-12-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0004_remove_order_note_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
