# Generated by Django 4.1.3 on 2022-12-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("highlight", "0007_highlight_remove_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highlight",
            name="highlight_product",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
