# Generated by Django 3.2.8 on 2022-12-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_list',
            field=models.JSONField(null=True),
        ),
    ]
