# Generated by Django 4.1.3 on 2022-12-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_initial'),
        ('order', '0002_alter_order_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
